//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProblemaProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SisteEntities : DbContext
    {
        public SisteEntities()
            : base("name=SisteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<genero> generoes { get; set; }
        public virtual DbSet<pelicula> peliculas { get; set; }
    
        [DbFunction("SisteEntities", "pDisp")]
        public virtual IQueryable<pDisp_Result> pDisp(Nullable<int> mid)
        {
            var midParameter = mid.HasValue ?
                new ObjectParameter("mid", mid) :
                new ObjectParameter("mid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<pDisp_Result>("[SisteEntities].[pDisp](@mid)", midParameter);
        }
        //public virtual IQueryable<pDisp_Result> pDisp(Nullable<int> mid)
    
        [DbFunction("SisteEntities", "pRen")]
        public virtual IQueryable<pRen_Result> pRen(Nullable<int> mid)
        {
            var midParameter = mid.HasValue ?
                new ObjectParameter("mid", mid) :
                new ObjectParameter("mid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<pRen_Result>("[SisteEntities].[pRen](@mid)", midParameter);
        }
    
        public virtual int finRenta(Nullable<int> mid)
        {
            var midParameter = mid.HasValue ?
                new ObjectParameter("mid", mid) :
                new ObjectParameter("mid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("finRenta", midParameter);
        }
    
        public virtual int Rentar(Nullable<int> mid)
        {
            var midParameter = mid.HasValue ?
                new ObjectParameter("mid", mid) :
                new ObjectParameter("mid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rentar", midParameter);
        }

        public System.Data.Entity.DbSet<ProblemaProject.Models.pDisp_Result> pDisp_Result { get; set; }

        public System.Data.Entity.DbSet<ProblemaProject.Models.pRen_Result> pRen_Result { get; set; }
    }
}
